pipeline {

    agent any

    tools {
    nodejs 'node18'
    }

    environment {

        // Jenkins credential ID
        DOCKERHUB_CREDS = credentials('dockerhub')

        DOCKERHUB_USERNAME = "${DOCKERHUB_CREDS_USR}"
        DOCKERHUB_PASSWORD = "${DOCKERHUB_CREDS_PSW}"

        FRONTEND_IMAGE = "${DOCKERHUB_USERNAME}/netflix-frontend"
        BACKEND_IMAGE  = "${DOCKERHUB_USERNAME}/netflix-backend"

        IMAGE_TAG = "${BUILD_NUMBER}"

        REACT_APP_API_URL = "http://netflix-backend-service:5000"
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        timestamps()
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/sabarikarthick7/netflix-devops-project.git'
            }
        }

        stage('Install Dependencies') {
            parallel {

                stage('Backend Dependencies') {
                    steps {
                        dir('backend') {
                            sh 'npm install'
                        }
                    }
                }

                stage('Frontend Dependencies') {
                    steps {
                        dir('frontend') {
                            sh 'npm install'
                        }
                    }
                }

            }
        }

        stage('Run Tests') {
            parallel {

                stage('Backend Tests') {
                    steps {
                        dir('backend') {
                            sh 'npm test || true'
                        }
                    }
                }

                stage('Frontend Tests') {
                    steps {
                        dir('frontend') {
                            sh 'CI=true npm test -- --passWithNoTests'
                        }
                    }
                }

            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh '''
                    export REACT_APP_API_URL=${REACT_APP_API_URL}
                    npm run build
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                sh '''
                echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                '''
            }
        }

        stage('Build Docker Images') {
            parallel {

                stage('Build Backend Image') {
                    steps {
                        dir('backend') {
                            sh '''
                            docker build -t ${BACKEND_IMAGE}:${IMAGE_TAG} .
                            docker tag ${BACKEND_IMAGE}:${IMAGE_TAG} ${BACKEND_IMAGE}:latest
                            '''
                        }
                    }
                }

                stage('Build Frontend Image') {
                    steps {
                        dir('frontend') {
                            sh '''
                            docker build -t ${FRONTEND_IMAGE}:${IMAGE_TAG} .
                            docker tag ${FRONTEND_IMAGE}:${IMAGE_TAG} ${FRONTEND_IMAGE}:latest
                            '''
                        }
                    }
                }

            }
        }

        stage('Push Docker Images') {
            parallel {

                stage('Push Backend Image') {
                    steps {
                        sh '''
                        docker push ${BACKEND_IMAGE}:${IMAGE_TAG}
                        docker push ${BACKEND_IMAGE}:latest
                        '''
                    }
                }

                stage('Push Frontend Image') {
                    steps {
                        sh '''
                        docker push ${FRONTEND_IMAGE}:${IMAGE_TAG}
                        docker push ${FRONTEND_IMAGE}:latest
                        '''
                    }
                }

            }
        }

    }

    post {

        always {
            echo 'Pipeline finished'
        }

        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed. Check logs.'
        }

    }

}